name: Build

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Lint Source
        run: |
          npm run clean
          npm run lint:extension

      - name: Build
        run: |
          tsc

      - name: Lint package
        run: |
          npm run lint:package

      - name: Create archive artifact
        run: |
          make pack

      - name: Create ZipFile Name
        run: echo "zipFileName=gestureImprovements.$(date --iso-8601).$(git rev-parse --short HEAD)@gestures.shell-extension.zip" >> $GITHUB_ENV

      - name: Upload archive artifact
        uses: "actions/upload-artifact@v4"
        with:
          name: ${{ env.zipFileName }}
          path: ${{ github.workspace }}/build/gestureImprovements@gestures.shell-extension.zip
